### ISSUE TITLE
Error with checkCredentials

### ISSUE THREAD

**Issue by jesugmz** [venomous0x/WhatsAPI#480]
Hi,

I try this code:
$w = new WhatsProt('CountryCodeMyTlf', 'IdentityObtainedWithMissvenom2.6', 'SomeNick', true);
$w->connect();
$w->LoginWithPassword('CodeObtainedWithCodeRequestMethod');
print_r($w->checkCredentials());
and I obtained this error:
Array ( [cc] => XX [in] => XXXXXXXXX [id] => bgp%XX%XX%XXX%XX%XX%XX%XXX%XX%XX%XX%XX%XX%XXX%XX [c] => cookie ) stdClass Object ( [status] => fail [reason] => incorrect [sms_length] => 6 [voice_length] => 6 ) 
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\xampp\htdocs\WhatsAPI\src\php\whatsprot.class.php:145 Stack trace: #0 C:\xampp\htdocs\WhatsAPI\src\php\example.php(13): WhatsProt->checkCredentials() #1 {main} thrown in C:\xampp\htdocs\WhatsAPI\src\php\whatsprot.class.php on line 145

My IdentityObtainedWithMissvenom2.6 have 28 characters and contain a / (slash) character, It´s normal? I try my IMEI code too in this field and I get the same error.

The codeRequest method return me a number with this format XXX-XXX, it´s normal too?

I have active openSSL extension in php.ini

I try with an old iPhone account.

Thx you for help.

**Comment by NakulSharmaIt** [comment]
Dear All...

Is it necessary to put sim inside the mobile phone while registering/requesting for code via sms/call because while requesting for code it is showing :

By Wart:
SMS: {status:fail, reason: no_routes, retry_after: 3600}
Voice: {status:fail, reason: no_routes, retry_after: 3600}

& By exampleRegister.php

Array
(
[in] => 8010202508
[cc] => 91
[id] => %93%c6%7f%38%a5%c2%4b%02%a0%d8%9e%54%c8%e0%6f%5a
[lg] => hi
[lc] => IN
[mcc] => 000
[mnc] => 000
[sim_mcc] => 404
[sim_mnc] => 000
[method] => sms
[reason] => self-send-jailbroken
[token] => elT4fXmNLXnunctHOv%2BZdkVWI4o%3D
[network_radio_type] => 1
)
stdClass Object
(
[status] => fail
[reason] => no_routes
[retry_after] => 3600
)

So i have to change sim every time & it is very tough to put sim inside phone every time.

So help me in both case:
1. no_routes
2. Sim in side mobile or not
